server:
  port: 8091
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: authService
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/e-auction/api/v1/auth/**
        filters:
        - name: CircuitBreaker
          args:
            name: gatewayCircuitBreaker
            fallbackUri: forward:/fallback/message        
      - id: auctionCmdService
        uri: lb://AUCTION-CMD-SERVICE
        predicates:
        - Path=/e-auction/api/v1/cmd/**
        filters:
        - JwtAuthenticationFilter
        - name: CircuitBreaker
          args:
            name: gatewayCircuitBreaker
            fallbackUri: forward:/fallback/message
      - id: auctionQueryService
        uri: lb://AUCTION-QUERY-SERVICE
        predicates:
        - Path=/e-auction/api/v1/query/**
        filters:
        - JwtAuthenticationFilter
        - name: CircuitBreaker
          args:
            name: gatewayCircuitBreaker
            fallbackUri: forward:/fallback/message
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
jwt:
  secret: c9998dbc291932efc08976fbfa62e55567176134c70f34a200b0b6883f19f30c
  token:
    validity: 18000000
 
api:
  endpoints: 
    noauth: /login, /register
    